### ISSUE TITLE
本地启动

### ISSUE THREAD

**Issue by Ihavedreams** [zhaoky/flqin#16]
请问一个本地启动报错问题，如下图：
![image](https://user-images.githubusercontent.com/40274448/91304819-ae38c980-e7dc-11ea-9846-b9e991153d6d.png)

**Comment by Ihavedreams** [comment]
![image](https://user-images.githubusercontent.com/40274448/91305564-cb21cc80-e7dd-11ea-884a-3e7cac50bc9d.png)

**Comment by zhaoky** [comment]
@Ihavedreams  图示并没有报错，并且master已更新最新版本的代码，欢迎查阅！

**Comment by yolo-612** [comment]
<img width="578" alt="image" src="https://github.com/zhaoky/flqin/assets/45038383/1d9467f6-311c-479c-8eb1-05a7d90c2c2c">

**Comment by yolo-612** [comment]
本地启动后编译无错误是什么原因导致的
