### ISSUE TITLE
CentOS 6.1 64位执行到gulp dd报错

### ISSUE THREAD

**Issue by zhihuanwang** [zhaoky/flqin#3]
在远程CentOS 6.1 64位执行到gulp dd报错，报错信息为:

>  Your [shelljs] version is too High,
> For Stable,Please Install V0.7.6!
> 
> Potentially unhandled rejection [2] '../_rdefault/cmpt.less' wasn't found. Tried - /home/centos/src/components/_rdefault/cmpt.less,../_rdefault/cmpt.less in file /home/centos/src/components/rMain/cmpt.less line no. 2
> webpack 热执行完成!
> [11:54:46] webpack is watching for changes
> [11:54:46] gulp-imagemin: Minified 22 images (saved 17.7 kB - 27.5%)
> 

node版本为v6.11.5

但我在windows7本地主机上可以正常运行，运行结果：

> 
> Your [shelljs] version is too High,
> For Stable,Please Install V0.7.6!
> 
> webpack 热执行完成!
> [11:57:26] webpack is watching for changes
> [11:57:29] gulp-imagemin: Minified 21 images (saved 16.5 kB - 35%)
> ----- V5! All DONE!!
> [11:57:29] Finished 'dev' after 14 s
> [11:57:29] Starting 'dd'...
> [11:57:29] Finished 'dd' after 390 ms
> [11:57:29] Server started http://localhost:8888
> 

可以访问到http://localhost:8888/
node版本也为v6.11.5

**Comment by zhaoky** [comment]
CentOS里可能某个node包 没有安装好/版本不对

**Comment by zhihuanwang** [comment]
请问在CentOS 6.1 64位中哪个node版本可以呢？或者说你的简历项目放在哪类服务器上能告知吗

**Comment by Insistem** [comment]
请问如何部署到云服务器上 , 让网络上的人都可以访问到 , 而不是部署在本地 , 只有自己可以访问到??

**Comment by zhihuanwang** [comment]
你可不可以把centos里可以正常的node版本和所需依赖告知一下，谢谢

**Comment by zhaoky** [comment]
抱歉，此项目很久未维护，近期会重构一版，再次抱歉！
