### ISSUE TITLE
网站不兼容firefox quantum 67 for linux

### ISSUE THREAD

**Issue by a7a2** [zhaoky/flqin#5]
网站不兼容firefox quantum 67 for linux

表现为鼠标或键盘上下左右按键 都不能使页面滚到下一个页面

只有右边的小圆圈点击了才看到

**Comment by zhaoky** [comment]
谢谢反馈，尽快处理。

**Comment by zhaoky** [comment]
@a7a2  已处理，有问题请继续反馈，谢谢！
