### ISSUE TITLE
随便问问

### ISSUE THREAD

**Issue by begonia9193** [zhaoky/flqin#8]
我记得之前看这个项目的时候，还是react的那一套，对吧？今天看的时候，感觉变化好大，重构过了吗？

**Comment by zhaoky** [comment]
@Jieyuhua9193  是这样的，之前那一套是用的 angular1 加 gulp 开发的，长时间未更新，技术过于陈旧。所以这次重构了一版，用的自己写的mvvm来代替ng实现数据绑定和视图更新，就没用框架了
